//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yearnly.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemComment
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int UserId { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual UserItem UserItem { get; set; }
        public virtual UserProfile CommenterProfile { get; set; }
    }
}
